camera:
  type: "realsense" # realsense, d-robotics, zed, zed_compressed, orbbec 根据相机的类型，选择对应的type
  intrin:
    fx: 643.898
    fy: 643.216
    cx: 649.038
    cy: 357.21
    distortion_coeffs: [-0.0553056,0.065975,-0.000994232,2.98548e-05,-0.0216579]
    distortion_model: 2 # 0: none, 1: opencv format, 2: for rs d455 only
  extrin:
    - [ 0.05659255, 0.03014561, 0.99794215, 0.04217854]
    - [-0.99839673, 0.00283376, 0.05653273, 0.01405556]
    - [-0.00112372,-0.9995415 , 0.03025765,-0.01538294]
    - [ 0.        , 0.        , 0.        , 1.        ]
  pitch_compensation: 0.0 # in degree
  yaw_compensation: 0.0
  z_compensation: 0.0
detection_model:
  model_path: "./src/vision/model/best_orin_10.3.engine"
  confidence_threshold: 0.2
  nms_threshold: 0.4
  classnames: ["Ball", "Goalpost", "Person", "LCross", "TCross", "XCross", "PenaltyPoint", "Opponent", "BRMarker"]
  post_process:
    single_ball_assumption: false
    confidence_thresholds:
      Ball: 0.4
      Goalpost: 0.4
      Person: 0.4
      LCross: 0.3
      TCross: 0.3
      XCross: 0.3
      PenaltyPoint: 0.3
      Opponent: 0.4
      BRMarker: 0.2
segmentation_model:
  model_path: "./src/vision/model/best_seg_orin_10.3.engine"
  confidence_threshold: 0.3
  nms_threshold: 0.9
# robot_color_classifier:
#   red_bounds:
#     - [0, 80, 50, 20, 255, 255]
#     - [160, 80, 100, 179, 255, 255]
#   blue_bounds:
#     - [100, 140, 50, 140, 255, 255]
#   green_bounds:
#     - [30, 45, 45, 80, 255, 255]
use_depth: true
ball_pose_estimator:
  use_depth: false
  radius: 0.109
  down_sample_leaf_size: 0.01
  cluster_distance_threshold: 0.01
  fitting_distance_threshold: 0.01
  minimum_cluster_size: 150
  filter_distance: 1.2
  check_ball_height: true
human_like_pose_estimator:
  use_depth: false
  down_sample_leaf_size: 0.01
  fitting_distance_threshold: 0.01
  statistic_outlier_multiplier: 0.01
field_marker_pose_estimator:
  refine: false
  line_segment_area_threshold: 75 # 75 for vga resolution, 300 for 720p resolution
calibration:
  offset:
    exclude_distance: 2.0
    zero_translation: true
    field_marker_path: "./src/vision/config/field.yaml"
misc:
  save_data_nonstationary: true
  
  
